site_name: encuestas-backend-django
site_description: Preinscripcion UNQ backend en Django
repo_url: https://github.com/Arquitectura1-Mottesi-Olmedo-Tolaba/encuestas-backend-django
site_dir: site
copyright: Copyright &copy; 2017, <a href="https://github.com/Arquitectura1-Mottesi-Olmedo-Tolaba">Arquitectura1-Mottesi-Olmedo-Tolaba</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
